import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import infoToolTipTemplate from "../components/info-tooltip/template";
import pinnedLocationLinkTemplate from "../components/pinned-location-link/template";

const Home: NextPage = () => {
  useEffect(() => {
    import("@webcomponents/template-shadowroot/template-shadowroot").then(
      (module) => {
        const { hasNativeDeclarativeShadowRoots, hydrateShadowRoots } = module;

        if (!hasNativeDeclarativeShadowRoots) {
          hydrateShadowRoots(document.body);
        }

        import("../components/info-tooltip/component").then(() => {
          console.log("Imported info-tooltip!");
        });

        import("../components/pinned-location-link/component").then(() => {
          console.log("Imported pinned-location-link!");
        });
      }
    );
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pinned-location-link
          data-place-name="Central Park"
          dangerouslySetInnerHTML={{
            __html: pinnedLocationLinkTemplate({
              placeName: "Empire State Building",
            }),
          }}
        />
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
          <info-tooltip
            data-text="Hello World!"
            dangerouslySetInnerHTML={{
              __html: infoToolTipTemplate({
                text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,\nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
              }),
            }}
          ></info-tooltip>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
};

export default Home;
